# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Using System.AccessToken to authenticate $(System.AccessToken)"
    git clone https://dev.azure.com/v-catherbund/cebundy%20-%20basic/_git/cebundy%20-%20basic
  displayName: 'Clone repository using System.AccessToken'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)