# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- pwsh: ./setvars.ps1
- task: PowerShell@2
  inputs:
    filePath: './helloworld.ps1'
    arguments: '-sauceArgument "$(sauce)" -secretSauceArgument "$(secret.Sauce)"'
# - pwsh: ./VersionAssemblies.ps1
- pwsh: echo $(Build.BuildNumber) //output updated build number


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Param(
         [string]$sauceArgument,
         [string]$secretSauceArgument
      )
      Write-Host No problem reading $env:SAUCE or $sauceArgument
      Write-Host But I cannot read $env:SECRET_SAUCE
      Write-Host But I can read $secretSauceArgument "(but the log is redacted so I do not
                 spoil the secret)"