# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- main

pool:
  vmImage: windows-latest

variables:
- name: var1
  value: 'var1'
- name: mySecret
  value: $(secret.Sauce)

steps:
# - pwsh: ./setvars.ps1
# - task: PowerShell@2
#   inputs:
#     filePath: './helloworld.ps1'
#     arguments: '-sauceArgument "$(sauce)" -secretSauceArgument "$(secret.Sauce)"'
# # - pwsh: ./VersionAssemblies.ps1

- pwsh: |
    az pipelines build list --organization $(System.TeamFoundationCollectionUri) --project $(System.TeamProject)
  displayName: 'Show build list '
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)  

# - pwsh: |
#    Write-Host "##vso[task.setvariable variable=sauce]peeled tomatoes"
#    Write-Host "##vso[task.setvariable variable=secret.Sauce;issecret=true]peeled tomatoes with garlic"
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your PowerShell commands here.

#       Write-Host No problem reading $(sauce)
#       Write-Host But I cannot read $env:SECRET_SAUCE
#       Write-Host But I can read $(secret.Sauce) (but the log is redacted so I do not spoil the secret)
#       Write-Host Can I read mySecret? $(mySecret)
#       Write-Host Can I read secret.sauce? $(secret.Sauce)
